---
guest_info:
  name: Test Vagrant Instance++
  memory: 2048
  threads: 2
  os: debian
  base_box: bento/ubuntu-16.04
  use_gui: false
  default_user: vagrant
  project_root: "../"
features:
- name: gem
  target: ceedling
- name: package_manager
  target: rake gcc libgl1-mesa-dev mesa-common-dev environment-modules gcc-arm-linux-gnueabihf
    build-essential automake pkg-config autopoint libtool gtk-doc-tools libglib2.0-dev
    gtk-doc-tools liborc-0.4-0 liborc-0.4-dev libvorbis-dev libcdparanoia-dev libcdparanoia0
    cdparanoia libvisual-0.4-0 libvisual-0.4-dev libvisual-0.4-plugins libvisual-projectm
    vorbis-tools vorbisgain libopus-dev libopus-doc libopus0 libopusfile-dev libopusfile0
    libtheora-bin libtheora-dev libtheora-doc libvpx-dev libvpx-doc libvpx3 libqt5gstreamer-1.0-0
    libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libflac++-dev libavc1394-dev
    libraw1394-dev libraw1394-tools libraw1394-doc libraw1394-tools libtag1-dev libtagc0-dev
    libwavpack-dev wavpack bison flex
sources:
    provider: git
    host: https://anongit.freedesktop.org/git/gstreamer/gst-plugins-good.git
  - name: gstreamer-plugins-good
    provider: git
    host: https://anongit.freedesktop.org/git/gstreamer/gst-plugins-bad.git
  - name: gstreamer-plugins-bad
    provider: git
    host: https://anongit.freedesktop.org/git/gstreamer/gst-plugins-base.git
  - name: gstreamer-plugins-base
    provider: git
    host: git://anongit.freedesktop.org/git/gstreamer/gstreamer
  - name: gstreamer
